### ISSUE TITLE
Option to disable messages

### ISSUE THREAD

**Issue by dassschaf** [askuri/ultimania-client#2]
While I see the benefit of having chat messages with Ultimatia records as you may be used to it from race servers with Dedimania, I'd love to see an option to disable them to have the "old" behaviour of the plugin back and to get rid of a bit of chat clutter, especially when a lot of new records are driven.

**Comment by askuri** [comment]
Thanks for the suggestion. I just pushed a commit that additionally to your idea also allows for setting the rank threshold at which a record improvement message is public or not.

**Comment by askuri** [comment]
Released with Ultimania 2.1.0: https://github.com/askuri/ultimania-client/releases/tag/v2.1.0
